# Generated by Django 3.2.9 on 2021-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('description', models.CharField(max_length=1024)),
                ('customer', models.CharField(max_length=100)),
                ('system', models.CharField(max_length=100)),
                ('attachment_path', models.CharField(max_length=200, null=True)),
                ('source_ip', models.CharField(max_length=100)),
            ],
        ),
    ]
