# Generated by Django 3.2.9 on 2021-11-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='guid',
            field=models.CharField(default='bad-guid', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
